In [1]:
lines = ['1. first\n', '2. second\n', '3. third\n']

f = open('text.txt', 'w')
f.writelines(lines)
f.close()

In [2]:
f = open('text.txt')
print(f.readline())
print(f.readline())
print(f.readline())
f.close()

1. first

2. second

3. third



In [3]:
f = open('text.txt')
print(f.readlines())
f.close()

['1. first\n', '2. second\n', '3. third\n']


In [4]:
f = open('text.txt')
lines = f.readlines()

import sys
sys.stdout.writelines(lines)

1. first
2. second
3. third


In [5]:
import glob
glob.glob('*.*')

['Convolution filter visualization.ipynb',
 'MLP1.ipynb',
 'ship.ipynb',
 'text.txt',
 'tmp.npy',
 'Untitled.ipynb',
 'Untitled1.ipynb',
 'Untitled2.ipynb']

In [2]:
import numpy as np
a = np.zeros((2,2))  # Create an array of all zeros
print(a)

[[0. 0.]
 [0. 0.]]


In [3]:
b = np.ones((4,4,3))   # Create an array of all ones
print(b) 

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [27]:
c = np.full((2,2), 7) # Create a constant array
print(c)

[[7 7]
 [7 7]]


In [29]:
e = np.random.random((2,2)) # Create an array filled with random values
print(e)

[[0.71295867 0.06359067]
 [0.80052694 0.62240993]]


In [39]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:3, :3]
print(b)

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]


In [44]:
print(a[0, 1])  
b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print(b[0, 1])

2
2
